export const specialties = [
  { name: "Computer Vision", slug: "computer-vision", accent: "#38bdf8" },
  { name: "NLP", slug: "nlp", accent: "#818cf8" },
  { name: "LLM / Generative AI", slug: "llm", accent: "#c084fc" },
  { name: "Tabular", slug: "tabular", accent: "#2dd4bf" },
  { name: "Audio", slug: "audio", accent: "#fb7185" },
  { name: "Time Series", slug: "time-series", accent: "#fbbf24" },
] as const;

export type SpecialtyName = (typeof specialties)[number]["name"];

export type Kaggler = {
  username: string;
  displayName: string;
  tier: "Grandmaster" | "Master" | "Expert";
  country: string;
  officialRank: number;
  highestRank: number;
  careerPower: number;
  soloPower: number | null;
  consistency: number;
  momentum: number;
  competitionCount: number;
  medals: { gold: number; silver: number; bronze: number };
  specialties: { name: SpecialtyName; score: number }[];
  joinedYear: number;
};

export const kagglers: Kaggler[] = [
  {
    username: "metricmuse",
    displayName: "Lina Park",
    tier: "Grandmaster",
    country: "South Korea",
    officialRank: 8,
    highestRank: 3,
    careerPower: 99.8,
    soloPower: 97.4,
    consistency: 98.9,
    momentum: 94.6,
    competitionCount: 64,
    medals: { gold: 12, silver: 18, bronze: 21 },
    specialties: [
      { name: "Computer Vision", score: 99 },
      { name: "Tabular", score: 94 },
      { name: "NLP", score: 91 },
    ],
    joinedYear: 2018,
  },
  {
    username: "gridsearcher",
    displayName: "Mateo Ruiz",
    tier: "Grandmaster",
    country: "Spain",
    officialRank: 14,
    highestRank: 6,
    careerPower: 99.5,
    soloPower: 98.7,
    consistency: 97.8,
    momentum: 96.8,
    competitionCount: 58,
    medals: { gold: 10, silver: 17, bronze: 16 },
    specialties: [
      { name: "Tabular", score: 99 },
      { name: "Time Series", score: 96 },
      { name: "NLP", score: 82 },
    ],
    joinedYear: 2019,
  },
  {
    username: "latentfox",
    displayName: "Aiko Mori",
    tier: "Grandmaster",
    country: "Japan",
    officialRank: 21,
    highestRank: 9,
    careerPower: 99.1,
    soloPower: 95.8,
    consistency: 96.5,
    momentum: 98.1,
    competitionCount: 47,
    medals: { gold: 9, silver: 13, bronze: 15 },
    specialties: [
      { name: "LLM / Generative AI", score: 99 },
      { name: "NLP", score: 98 },
      { name: "Computer Vision", score: 88 },
    ],
    joinedYear: 2020,
  },
  {
    username: "bayesrunner",
    displayName: "Noah Williams",
    tier: "Grandmaster",
    country: "Canada",
    officialRank: 27,
    highestRank: 11,
    careerPower: 98.7,
    soloPower: 96.2,
    consistency: 97.2,
    momentum: 91.5,
    competitionCount: 71,
    medals: { gold: 8, silver: 16, bronze: 24 },
    specialties: [
      { name: "Tabular", score: 97 },
      { name: "Time Series", score: 94 },
      { name: "NLP", score: 79 },
    ],
    joinedYear: 2017,
  },
  {
    username: "pixelpilot",
    displayName: "Sofia Chen",
    tier: "Grandmaster",
    country: "Singapore",
    officialRank: 35,
    highestRank: 18,
    careerPower: 98.2,
    soloPower: 91.4,
    consistency: 95.9,
    momentum: 97.3,
    competitionCount: 42,
    medals: { gold: 7, silver: 12, bronze: 14 },
    specialties: [
      { name: "Computer Vision", score: 98 },
      { name: "LLM / Generative AI", score: 93 },
      { name: "NLP", score: 87 },
    ],
    joinedYear: 2021,
  },
  {
    username: "vectornorth",
    displayName: "Emil Larsson",
    tier: "Master",
    country: "Sweden",
    officialRank: 52,
    highestRank: 31,
    careerPower: 97.6,
    soloPower: 94.9,
    consistency: 94.8,
    momentum: 92.7,
    competitionCount: 39,
    medals: { gold: 5, silver: 11, bronze: 13 },
    specialties: [
      { name: "NLP", score: 95 },
      { name: "LLM / Generative AI", score: 94 },
      { name: "Tabular", score: 84 },
    ],
    joinedYear: 2019,
  },
  {
    username: "foldartisan",
    displayName: "Priya Nair",
    tier: "Master",
    country: "India",
    officialRank: 68,
    highestRank: 40,
    careerPower: 96.9,
    soloPower: 90.6,
    consistency: 96.1,
    momentum: 95.2,
    competitionCount: 51,
    medals: { gold: 4, silver: 13, bronze: 18 },
    specialties: [
      { name: "Tabular", score: 96 },
      { name: "Time Series", score: 93 },
      { name: "NLP", score: 86 },
    ],
    joinedYear: 2018,
  },
  {
    username: "spectralowl",
    displayName: "Omar Haddad",
    tier: "Master",
    country: "UAE",
    officialRank: 74,
    highestRank: 43,
    careerPower: 96.4,
    soloPower: 92.1,
    consistency: 93.5,
    momentum: 89.4,
    competitionCount: 36,
    medals: { gold: 4, silver: 9, bronze: 12 },
    specialties: [
      { name: "Audio", score: 98 },
      { name: "Computer Vision", score: 89 },
      { name: "NLP", score: 81 },
    ],
    joinedYear: 2020,
  },
  {
    username: "tensortrail",
    displayName: "Grace Miller",
    tier: "Master",
    country: "United States",
    officialRank: 83,
    highestRank: 48,
    careerPower: 95.8,
    soloPower: 93.5,
    consistency: 92.7,
    momentum: 96.1,
    competitionCount: 33,
    medals: { gold: 3, silver: 10, bronze: 11 },
    specialties: [
      { name: "Computer Vision", score: 96 },
      { name: "LLM / Generative AI", score: 92 },
      { name: "Tabular", score: 83 },
    ],
    joinedYear: 2021,
  },
  {
    username: "kernelcraft",
    displayName: "Louis Bernard",
    tier: "Master",
    country: "France",
    officialRank: 97,
    highestRank: 55,
    careerPower: 95.1,
    soloPower: 88.9,
    consistency: 94.1,
    momentum: 87.8,
    competitionCount: 45,
    medals: { gold: 3, silver: 9, bronze: 17 },
    specialties: [
      { name: "Tabular", score: 95 },
      { name: "Time Series", score: 90 },
      { name: "Computer Vision", score: 78 },
    ],
    joinedYear: 2018,
  },
  {
    username: "lossweaver",
    displayName: "Nadia Petrova",
    tier: "Master",
    country: "Bulgaria",
    officialRank: 112,
    highestRank: 64,
    careerPower: 94.6,
    soloPower: 91.7,
    consistency: 91.9,
    momentum: 93.8,
    competitionCount: 31,
    medals: { gold: 3, silver: 8, bronze: 10 },
    specialties: [
      { name: "NLP", score: 96 },
      { name: "LLM / Generative AI", score: 91 },
      { name: "Audio", score: 80 },
    ],
    joinedYear: 2021,
  },
  {
    username: "boostforge",
    displayName: "Daniel Kim",
    tier: "Master",
    country: "Australia",
    officialRank: 126,
    highestRank: 71,
    careerPower: 93.9,
    soloPower: 86.3,
    consistency: 93.2,
    momentum: 84.6,
    competitionCount: 49,
    medals: { gold: 2, silver: 9, bronze: 19 },
    specialties: [
      { name: "Tabular", score: 94 },
      { name: "Time Series", score: 88 },
      { name: "NLP", score: 77 },
    ],
    joinedYear: 2017,
  },
  {
    username: "auralattice",
    displayName: "Camila Torres",
    tier: "Expert",
    country: "Brazil",
    officialRank: 143,
    highestRank: 102,
    careerPower: 92.8,
    soloPower: 89.8,
    consistency: 89.7,
    momentum: 94.9,
    competitionCount: 27,
    medals: { gold: 2, silver: 7, bronze: 9 },
    specialties: [
      { name: "Audio", score: 96 },
      { name: "Time Series", score: 87 },
      { name: "NLP", score: 85 },
    ],
    joinedYear: 2022,
  },
  {
    username: "tabularis",
    displayName: "Jonas Weber",
    tier: "Expert",
    country: "Germany",
    officialRank: 159,
    highestRank: 110,
    careerPower: 91.9,
    soloPower: 87.2,
    consistency: 90.8,
    momentum: 82.5,
    competitionCount: 34,
    medals: { gold: 1, silver: 8, bronze: 13 },
    specialties: [
      { name: "Tabular", score: 93 },
      { name: "Time Series", score: 89 },
      { name: "Computer Vision", score: 71 },
    ],
    joinedYear: 2019,
  },
  {
    username: "sequencebay",
    displayName: "Mina Ito",
    tier: "Expert",
    country: "Japan",
    officialRank: 177,
    highestRank: 121,
    careerPower: 90.7,
    soloPower: null,
    consistency: 88.6,
    momentum: 92.1,
    competitionCount: 19,
    medals: { gold: 1, silver: 6, bronze: 8 },
    specialties: [
      { name: "NLP", score: 93 },
      { name: "LLM / Generative AI", score: 90 },
      { name: "Time Series", score: 73 },
    ],
    joinedYear: 2023,
  },
  {
    username: "visionquill",
    displayName: "Theo Martin",
    tier: "Expert",
    country: "United Kingdom",
    officialRank: 194,
    highestRank: 138,
    careerPower: 89.6,
    soloPower: 85.4,
    consistency: 87.9,
    momentum: 90.3,
    competitionCount: 24,
    medals: { gold: 1, silver: 5, bronze: 9 },
    specialties: [
      { name: "Computer Vision", score: 92 },
      { name: "LLM / Generative AI", score: 86 },
      { name: "Tabular", score: 70 },
    ],
    joinedYear: 2022,
  },
  {
    username: "chronomodel",
    displayName: "Elena Rossi",
    tier: "Expert",
    country: "Italy",
    officialRank: 216,
    highestRank: 149,
    careerPower: 88.4,
    soloPower: 83.7,
    consistency: 89.3,
    momentum: 85.1,
    competitionCount: 29,
    medals: { gold: 1, silver: 5, bronze: 11 },
    specialties: [
      { name: "Time Series", score: 94 },
      { name: "Tabular", score: 88 },
      { name: "NLP", score: 68 },
    ],
    joinedYear: 2020,
  },
  {
    username: "embeddingsea",
    displayName: "Ahmed Saleh",
    tier: "Expert",
    country: "Egypt",
    officialRank: 238,
    highestRank: 164,
    careerPower: 87.2,
    soloPower: null,
    consistency: 84.8,
    momentum: 91.2,
    competitionCount: 17,
    medals: { gold: 1, silver: 4, bronze: 7 },
    specialties: [
      { name: "LLM / Generative AI", score: 92 },
      { name: "NLP", score: 89 },
      { name: "Computer Vision", score: 66 },
    ],
    joinedYear: 2023,
  },
  {
    username: "signalnest",
    displayName: "Julia Novak",
    tier: "Expert",
    country: "Poland",
    officialRank: 261,
    highestRank: 181,
    careerPower: 85.9,
    soloPower: 82.1,
    consistency: 86.7,
    momentum: 83.4,
    competitionCount: 26,
    medals: { gold: 0, silver: 6, bronze: 10 },
    specialties: [
      { name: "Audio", score: 91 },
      { name: "Time Series", score: 84 },
      { name: "NLP", score: 79 },
    ],
    joinedYear: 2021,
  },
  {
    username: "calibratedcat",
    displayName: "Ravi Shah",
    tier: "Expert",
    country: "India",
    officialRank: 289,
    highestRank: 204,
    careerPower: 84.5,
    soloPower: 80.8,
    consistency: 85.1,
    momentum: 88.6,
    competitionCount: 22,
    medals: { gold: 0, silver: 5, bronze: 8 },
    specialties: [
      { name: "Tabular", score: 90 },
      { name: "Computer Vision", score: 82 },
      { name: "Time Series", score: 80 },
    ],
    joinedYear: 2022,
  },
];

export function getKaggler(username: string) {
  return kagglers.find((kaggler) => kaggler.username === username);
}

export function getInitials(displayName: string) {
  return displayName
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}
